<Project>
    <PropertyGroup Label="Build Profile">
        <IkvmDefaultSupportedRuntimes>win-x64;win-x86;win-arm64;linux-x64;linux-arm;linux-arm64;linux-musl-x64;linux-musl-arm;linux-musl-arm64;osx-x64;osx-arm64</IkvmDefaultSupportedRuntimes>
        <IkvmDefaultSupportedImageRuntimes>$(IkvmDefaultSupportedRuntimes)</IkvmDefaultSupportedImageRuntimes>
        <IkvmDefaultSupportedImageBinRuntimes>$(IkvmDefaultSupportedRuntimes)</IkvmDefaultSupportedImageBinRuntimes>
        <IkvmDefaultSupportedToolRuntimes>win-x64;win-arm64;linux-x64;linux-arm;linux-arm64;linux-musl-x64;linux-musl-arm;linux-musl-arm64;osx-x64;osx-arm64</IkvmDefaultSupportedToolRuntimes>
        <IkvmRunningInCi Condition=" '$(IkvmRunningInCi)' == '' And ('$(ContinuousIntegrationBuild)' == 'true' Or '$(CI)' == 'true' Or '$(TF_BUILD)' == 'True' Or '$(GITHUB_ACTIONS)' == 'true') ">true</IkvmRunningInCi>
        <IkvmRunningInCi Condition=" '$(IkvmRunningInCi)' == '' ">false</IkvmRunningInCi>
        <IkvmBuildForPackaging Condition=" '$(IkvmBuildForPackaging)' == '' And ('$(Pack)' == 'true' Or '$(PackIkvmJava)' == 'true' Or '$(PackIkvmLibs)' == 'true') ">true</IkvmBuildForPackaging>
        <IkvmBuildForPackaging Condition=" '$(IkvmBuildForPackaging)' == '' ">false</IkvmBuildForPackaging>
        <IkvmFastLocalBuild Condition=" '$(IkvmFastLocalBuild)' == '' And '$(IkvmRunningInCi)' != 'true' And '$(IkvmBuildForPackaging)' != 'true' ">true</IkvmFastLocalBuild>
        <IkvmFastLocalBuild Condition=" '$(IkvmFastLocalBuild)' == '' ">false</IkvmFastLocalBuild>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">win-x64</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X86'">win-x86</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'ARM64'">win-arm64</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Linux')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">linux-x64</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Linux')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'ARM'">linux-arm</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Linux')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'ARM64'">linux-arm64</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('OSX')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">osx-x64</IkvmHostRuntimeIdentifier>
        <IkvmHostRuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('OSX')) And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'ARM64'">osx-arm64</IkvmHostRuntimeIdentifier>
        <IkvmLocalRuntimes Condition=" '$(IkvmLocalRuntimes)' == '' ">$(IkvmHostRuntimeIdentifier)</IkvmLocalRuntimes>
        <IkvmBuildJavaWindowsRuntime Condition=" '$(IkvmBuildJavaWindowsRuntime)' == '' And '$(IkvmBuildForPackaging)' == 'true' ">true</IkvmBuildJavaWindowsRuntime>
        <IkvmBuildJavaWindowsRuntime Condition=" '$(IkvmBuildJavaWindowsRuntime)' == '' And '$(IkvmFastLocalBuild)' == 'true' And $([MSBuild]::IsOSPlatform('Windows')) ">true</IkvmBuildJavaWindowsRuntime>
        <IkvmBuildJavaWindowsRuntime Condition=" '$(IkvmBuildJavaWindowsRuntime)' == '' ">false</IkvmBuildJavaWindowsRuntime>
        <IkvmBuildJavaLinuxRuntime Condition=" '$(IkvmBuildJavaLinuxRuntime)' == '' And '$(IkvmBuildForPackaging)' == 'true' ">true</IkvmBuildJavaLinuxRuntime>
        <IkvmBuildJavaLinuxRuntime Condition=" '$(IkvmBuildJavaLinuxRuntime)' == '' And '$(IkvmFastLocalBuild)' == 'true' And $([MSBuild]::IsOSPlatform('Linux')) ">true</IkvmBuildJavaLinuxRuntime>
        <IkvmBuildJavaLinuxRuntime Condition=" '$(IkvmBuildJavaLinuxRuntime)' == '' ">false</IkvmBuildJavaLinuxRuntime>
        <IkvmBuildJavaOsxRuntime Condition=" '$(IkvmBuildJavaOsxRuntime)' == '' And '$(IkvmBuildForPackaging)' == 'true' ">true</IkvmBuildJavaOsxRuntime>
        <IkvmBuildJavaOsxRuntime Condition=" '$(IkvmBuildJavaOsxRuntime)' == '' And '$(IkvmFastLocalBuild)' == 'true' And $([MSBuild]::IsOSPlatform('OSX')) ">true</IkvmBuildJavaOsxRuntime>
        <IkvmBuildJavaOsxRuntime Condition=" '$(IkvmBuildJavaOsxRuntime)' == '' ">false</IkvmBuildJavaOsxRuntime>
    </PropertyGroup>

    <PropertyGroup Label="Runtime Info">
        <SupportedRuntimes Condition=" '$(SupportedRuntimes)' == '' ">$(IkvmDefaultSupportedRuntimes)</SupportedRuntimes>
        <EnabledRuntimes Condition=" '$(EnabledRuntimes)' == '' ">$(SupportedRuntimes)</EnabledRuntimes>
        <SupportedImageRuntimes Condition=" '$(SupportedImageRuntimes)' == '' ">$(IkvmDefaultSupportedImageRuntimes)</SupportedImageRuntimes>
        <EnabledImageRuntimes Condition=" '$(EnabledImageRuntimes)' == '' ">$(SupportedImageRuntimes)</EnabledImageRuntimes>
        <SupportedImageBinRuntimes Condition=" '$(SupportedImageBinRuntimes)' == '' ">$(IkvmDefaultSupportedImageBinRuntimes)</SupportedImageBinRuntimes>
        <EnabledImageBinRuntimes Condition=" '$(EnabledImageBinRuntimes)' == '' ">$(SupportedImageBinRuntimes)</EnabledImageBinRuntimes>
        <SupportedToolRuntimes Condition=" '$(SupportedToolRuntimes)' == '' ">$(IkvmDefaultSupportedToolRuntimes)</SupportedToolRuntimes>
        <EnabledToolRuntimes Condition=" '$(EnabledToolRuntimes)' == '' ">$(SupportedToolRuntimes)</EnabledToolRuntimes>
    </PropertyGroup>

    <PropertyGroup Label="Fast Local Runtime Narrowing" Condition=" '$(IkvmFastLocalBuild)' == 'true' And '$(IkvmLocalRuntimes)' != '' ">
        <EnabledRuntimes Condition=" '$(EnabledRuntimes)' == '$(IkvmDefaultSupportedRuntimes)' ">$(IkvmLocalRuntimes)</EnabledRuntimes>
        <SupportedImageRuntimes Condition=" '$(SupportedImageRuntimes)' == '$(IkvmDefaultSupportedImageRuntimes)' ">$(IkvmLocalRuntimes)</SupportedImageRuntimes>
        <EnabledImageRuntimes Condition=" '$(EnabledImageRuntimes)' == '$(IkvmDefaultSupportedImageRuntimes)' ">$(IkvmLocalRuntimes)</EnabledImageRuntimes>
        <SupportedImageBinRuntimes Condition=" '$(SupportedImageBinRuntimes)' == '$(IkvmDefaultSupportedImageBinRuntimes)' ">$(IkvmLocalRuntimes)</SupportedImageBinRuntimes>
        <EnabledImageBinRuntimes Condition=" '$(EnabledImageBinRuntimes)' == '$(IkvmDefaultSupportedImageBinRuntimes)' ">$(IkvmLocalRuntimes)</EnabledImageBinRuntimes>
        <SupportedToolRuntimes Condition=" '$(SupportedToolRuntimes)' == '$(IkvmDefaultSupportedToolRuntimes)' ">$(IkvmLocalRuntimes)</SupportedToolRuntimes>
        <EnabledToolRuntimes Condition=" '$(EnabledToolRuntimes)' == '$(IkvmDefaultSupportedToolRuntimes)' ">$(IkvmLocalRuntimes)</EnabledToolRuntimes>
    </PropertyGroup>

    <PropertyGroup Label="Runtime Markers">
        <_SupportedRuntimes>;$(SupportedRuntimes);</_SupportedRuntimes>
        <_EnabledRuntimes>;$(EnabledRuntimes);</_EnabledRuntimes>
        <_SupportedImageRuntimes>;$(SupportedImageRuntimes);</_SupportedImageRuntimes>
        <_EnabledImageRuntimes>;$(EnabledImageRuntimes);</_EnabledImageRuntimes>
        <_SupportedImageBinRuntimes>;$(SupportedImageBinRuntimes);</_SupportedImageBinRuntimes>
        <_EnabledImageBinRuntimes>;$(EnabledImageBinRuntimes);</_EnabledImageBinRuntimes>
        <_SupportedToolRuntimes>;$(SupportedToolRuntimes);</_SupportedToolRuntimes>
        <_EnabledToolRuntimes>;$(EnabledToolRuntimes);</_EnabledToolRuntimes>
    </PropertyGroup>

    <PropertyGroup Label="OpenJDK Info">
        <OpenJdkDir>$(MSBuildThisFileDirectory)ext\openjdk\</OpenJdkDir>
        <OpenJdkMajorVersion>1</OpenJdkMajorVersion>
        <OpenJdkMinorVersion>8</OpenJdkMinorVersion>
        <OpenJdkMicroVersion>0</OpenJdkMicroVersion>
        <OpenJdkUpdateVersion>472</OpenJdkUpdateVersion>
        <OpenJdkBuildNumber>b08</OpenJdkBuildNumber>
        <OpenJdkVersion>OpenJDK $(OpenJdkMinorVersion)u$(OpenJdkUpdateVersion) $(OpenJdkBuildNumber)</OpenJdkVersion>
        <OpenJdkFullVersion>$(OpenJdkMajorVersion).$(OpenJdkMinorVersion).$(OpenJdkMicroVersion)_$(OpenJdkUpdateVersion)-$(OpenJdkBuildNumber)</OpenJdkFullVersion>
        <OpenJdkVendor>Oracle</OpenJdkVendor>
        <OpenJdkImplementationVersion>$(OpenJdkMajorVersion).$(OpenJdkMinorVersion).$(OpenJdkMicroVersion)</OpenJdkImplementationVersion>
        <OpenJdkImplementationVendor>Oracle Corporation</OpenJdkImplementationVendor>
        <OpenJdkSpecificationVersion>$(OpenJdkMajorVersion).$(OpenJdkMinorVersion)</OpenJdkSpecificationVersion>
        <OpenJdkSpecificationVendor>Oracle Corporation</OpenJdkSpecificationVendor>
    </PropertyGroup>

    <ItemGroup>
        <Authors Include="Jeroen Frijters" />
        <Authors Include="Jerome Haltom" />
    </ItemGroup>

    <PropertyGroup Label="Copyright Info">
        <ProductName>IKVM</ProductName>
        <Authors>@(Authors, ',')</Authors>
        <CurrentYear Condition=" '$(CurrentYear)' == '' ">$([System.DateTime]::UtcNow.Year.ToString())</CurrentYear>
        <Copyright>Copyright © $(CurrentYear) @(Authors, ', ')</Copyright>
    </PropertyGroup>

    <PropertyGroup Label="Version Info">
        <DefaultMajorVersion>8</DefaultMajorVersion>
        <Version Condition=" '$(Version)' == '' ">$(DefaultMajorVersion).0.0-dev</Version>
        <AssemblyVersion Condition=" '$(AssemblyVersion)' == '' ">$(DefaultMajorVersion).0.0.0</AssemblyVersion>
        <FileVersion Condition=" '$(FileVersion)' == '' ">$(DefaultMajorVersion).0.0.0</FileVersion>
        <InformationalVersion Condition=" '$(InformationalVersion)' == '' ">$(DefaultMajorVersion).0.0.0</InformationalVersion>
    </PropertyGroup>

    <PropertyGroup Label="Package Info">
        <RepositoryUrl Condition=" '$(RepositoryUrl)' == '' ">https://github.com/ikvmnet/ikvm.git</RepositoryUrl>
        <RepositoryType Condition=" '$(RepositoryType)' == '' ">git</RepositoryType>
        <PackageProjectUrl Condition=" '$(PackageProjectUrl)' == '' ">https://ikvm.org</PackageProjectUrl>
        <PackageVersion Condition=" '$(PackageVersion)' == '' ">$(Version)</PackageVersion>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Label="Build Info">
        <LangVersion Condition=" '$(LangVersion)' == '' ">12.0</LangVersion>
        <NoWarn>$(NoWarn);1591;1573;CS8002;NU5100;NU5118;NU5128;MSB3245;NETSDK1023;NETSDK1138</NoWarn>
        <AutoGenerateBindingRedirects Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net461'))">true</AutoGenerateBindingRedirects>
        <GenerateBindingRedirectsOutputType Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net461'))">true</GenerateBindingRedirectsOutputType>
        <AddSyntheticProjectReferencesForSolutionDependencies>false</AddSyntheticProjectReferencesForSolutionDependencies>
        <CopyRetryCount>60</CopyRetryCount>
        <CopyRetryDelayMilliseconds>15000</CopyRetryDelayMilliseconds>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    </PropertyGroup>

    <PropertyGroup Label="Assembly Info">
        <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)ikvm.snk</AssemblyOriginatorKeyFile>
        <PublicKey>0024000004800000940000000602000000240000525341310004000001000100dd6b140e5209cae3d1c710030021ef589d0f00d05aca8771101a7e99e10ee063e66040df96e6f842f717bfc5b62d2ec2b62ceb0282e4649790dacb424db29b68adc7eaeab0356fce04702379f84400b8427edbb33dab8720b9f16a42e2cdb87f885ef413dbc4229f2bd157c9b8dc2cd14866dec5f31c764bfb9394cc3c60e6c0</PublicKey>
        <SignAssembly Condition=" '$(AssemblyOriginatorKeyFile)' != '' ">true</SignAssembly>
    </PropertyGroup>

    <PropertyGroup Label="IKVM SDK">
        <IkvmCacheDir>$(MSBuildThisFileDirectory).ikvm\cache\1\</IkvmCacheDir>
        <IkvmExportCacheDir>$(MSBuildThisFileDirectory).ikvm\expcache\1\</IkvmExportCacheDir>
        <IkvmKeyFile>$(AssemblyOriginatorKeyFile)</IkvmKeyFile>
        <IkvmVersion>$(PackageVersion)</IkvmVersion>
        <UseIkvmTasks Condition=" '$(UseIkvmTasks)' == '' ">false</UseIkvmTasks>
        <UseIkvmToolReferences>true</UseIkvmToolReferences>
        <UseProjectJavaCompiler Condition=" '$(UseProjectJavaCompiler)' == '' ">false</UseProjectJavaCompiler>
        <DisableImplicitIkvmPackageReference>true</DisableImplicitIkvmPackageReference>
        <DisableImplicitIkvmMSBuildPackageReference>true</DisableImplicitIkvmMSBuildPackageReference>
    </PropertyGroup>

    <ItemGroup>
        <IkvmToolReference Include="$(MSBuildThisFileDirectory)src\javac-ref\javac-ref.ikvmproj" IsJavaCompiler="true" TargetFramework="net8.0" Condition=" '$(UseProjectJavaCompiler)' == 'true' " />
        <IkvmToolReference Include="$(MSBuildThisFileDirectory)src\ikvmc\ikvmc.csproj" IsIkvmCompiler="true" />
        <IkvmToolReference Include="$(MSBuildThisFileDirectory)src\ikvmstub\ikvmstub.csproj" IsIkvmExporter="true" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IKVM.Core.MSBuild" Version="0.1.106">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="IKVM.JdkUtil.MSBuild" Version="1.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
