<Project Sdk="MSTest.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net472;net6.0;net8.0;net10.0</TargetFrameworks>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
        <RunSettingsFilePath>$(MSBuildProjectDirectory)\IKVM.Tools.Exporter.Tests.runsettings</RunSettingsFilePath>
        <EnableMicrosoftTestingExtensionsCodeCoverage>false</EnableMicrosoftTestingExtensionsCodeCoverage>
        <DisableMsCoverageReferencedPathMaps>true</DisableMsCoverageReferencedPathMaps>
        <BuildInParallel>false</BuildInParallel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="6.8.0" />
		<PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net461'))">
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\IKVM.Runtime\IKVM.Runtime.csproj" />
        <ProjectReference Include="..\IKVM.Java\IKVM.Java.ikvmproj" />
        <ProjectReference Include="..\IKVM.Tools.Exporter\IKVM.Tools.Exporter.csproj" />
    </ItemGroup>

    <ItemGroup>
        <IncludeProjectReference Include="..\IKVM.Runtime\IKVM.Runtime.csproj" Condition=" '$(TargetFramework)' != 'net472' ">
            <SetTargetFramework>TargetFramework=net472</SetTargetFramework>
            <IncludeTargetPath>lib\net472\</IncludeTargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </IncludeProjectReference>
        <IncludeProjectReference Include="..\IKVM.Java\IKVM.Java.ikvmproj" Condition=" '$(TargetFramework)' != 'net472' ">
            <SetTargetFramework>TargetFramework=net472</SetTargetFramework>
            <IncludeTargetPath>lib\net472\</IncludeTargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </IncludeProjectReference>
        <IncludeProjectReference Include="..\IKVM.Runtime\IKVM.Runtime.csproj" Condition=" '$(TargetFramework)' != 'net6.0' ">
            <SetTargetFramework>TargetFramework=net6.0</SetTargetFramework>
            <IncludeTargetPath>lib\net6.0\</IncludeTargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </IncludeProjectReference>
        <IncludeProjectReference Include="..\IKVM.Java\IKVM.Java.ikvmproj" Condition=" '$(TargetFramework)' != 'net6.0' ">
            <SetTargetFramework>TargetFramework=net6.0</SetTargetFramework>
            <IncludeTargetPath>lib\net6.0\</IncludeTargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </IncludeProjectReference>
        <IncludeProjectReference Include="..\IKVM.Runtime\IKVM.Runtime.csproj" Condition=" '$(TargetFramework)' != 'net8.0' ">
            <SetTargetFramework>TargetFramework=net8.0</SetTargetFramework>
            <IncludeTargetPath>lib\net8.0\</IncludeTargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </IncludeProjectReference>
        <IncludeProjectReference Include="..\IKVM.Java\IKVM.Java.ikvmproj" Condition=" '$(TargetFramework)' != 'net8.0' ">
            <SetTargetFramework>TargetFramework=net8.0</SetTargetFramework>
            <IncludeTargetPath>lib\net8.0\</IncludeTargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </IncludeProjectReference>
    </ItemGroup>

    <Target Name="CopyCurrentFrameworkIkvmAssemblies" AfterTargets="Build">
        <ItemGroup>
            <_CurrentFrameworkIkvmAssemblies Include="@(ReferenceCopyLocalPaths)" Condition=" '%(Filename)' == 'IKVM.Runtime' Or '%(Filename)' == 'IKVM.Java' " />
        </ItemGroup>

        <MakeDir Directories="$(OutDir)lib\$(TargetFramework)\" Condition=" '@(_CurrentFrameworkIkvmAssemblies)' != '' " />
        <Copy SourceFiles="@(_CurrentFrameworkIkvmAssemblies)" DestinationFolder="$(OutDir)lib\$(TargetFramework)\" SkipUnchangedFiles="true" Condition=" '@(_CurrentFrameworkIkvmAssemblies)' != '' " />
    </Target>

    <ItemGroup>
        <None Update="IKVM.Tools.Exporter.Tests.runsettings">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
