<!--

    lib.targets
    
    Applies at the bottom of any native library project.

-->

<Project>
    <!-- Local Windows builds should not compile unavailable cross-platform native SDKs. -->
    <PropertyGroup Condition=" '$(IkvmFastLocalBuild)' == 'true' And '$(TargetIdentifier)' == '' ">
        <TargetIdentifiers>$(EnabledRuntimes)</TargetIdentifiers>
    </PropertyGroup>
    <PropertyGroup>
        <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    </PropertyGroup>

    <PropertyGroup Condition="$(TargetTriple.Contains('-apple-'))">
        <AdditionalLinkOptions>$(AdditionalLinkOptions);-Wl,-install_name,@rpath/lib$(TargetName).dylib</AdditionalLinkOptions>
    </PropertyGroup>

    <Import Project="$(MSBuildThisFileDirectory)ClangOSXCodeSign.targets"/>

</Project>
